### ISSUE TITLE
1.20.1 Support

### ISSUE THREAD

**Issue by SandrosMaximus** [Estecka/mc-I-See-You-Over-There#1]
Most big mods in 1.20 are for 1.20.1. 
Would love to see a backport for it

**Comment by Estecka** [comment]
The 1.19.4 branch is already compatible with 1.20.1.
Are you having trouble running it ?

**Comment by SandrosMaximus** [comment]
oh I didn't know that sorry. I just tried it and it works perfectly! great mod
